// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYyoewSu84Mb3CF7p7knQXiip8oQlSfA',
    appId: '1:113290054098:web:ee5d91e8ec6cf7ba93600b',
    messagingSenderId: '113290054098',
    projectId: 'mobileapplication-9a03d',
    authDomain: 'mobileapplication-9a03d.firebaseapp.com',
    storageBucket: 'mobileapplication-9a03d.firebasestorage.app',
    measurementId: 'G-1J2T18WHNP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYRojyI9I-zdxpWzf3F1khsfccKpO9fI',
    appId: '1:113290054098:ios:f54e9a52d31ec10193600b',
    messagingSenderId: '113290054098',
    projectId: 'mobileapplication-9a03d',
    storageBucket: 'mobileapplication-9a03d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
